### ISSUE TITLE
Use amazonlinux Docker image

### ISSUE THREAD

**Issue by fsenart** [eawsy/aws-lambda-go#11]
Amazon Linux Image now available on Docker Hub 
https://hub.docker.com/r/_/amazonlinux/

**Comment by jangaraj** [comment]
Why not tiny alpine docker image? Will it be binary compatibility problem (glibc vs musl)?

**Comment by cristim** [comment]
Alpine would be preferable indeed, due to its much smaller size it makes it much faster for developers to download it the first time they need it, but indeed it may be problematic due to the different libc, so it definitely needs to be tested first.

But then again, for humans this only matters when pulling the image for the first time, so it may not make much difference. But in my case I also use it from TravisCI, and it seems that the image is always downloaded fresh on each build, which is slower and wasteful with larger images.

I would really expect Travis and most other CI vendors to have a local registry caching proxy, not sure if they use this under the hood.

**Comment by fsenart** [comment]
@jangaraj as you've noticed, the problem with Alpine is musl. In the past we have tried to overcome this problem without success. That's why we've used a "regular" os as the base of the current Docker image.

@jangaraj @cristim, internally we also have a standalone gcc + go + libc + etc package that can be embedded in an Alpine image but this won't change anything. Indeed, Alpine images are more for production workloads (fast, minimal deployments) rather than development. In development, you need a bunch of different tools to be installed in the image, the effect is the growing size of the image.

Above explanations in mind, I opened the issue to "support"/"promote" the new AWS image. Why not using it, if we use already a regular OS as the base of the image.
One more advantage is also the fact that the AWS image along with contained libraries will be the one used by the AWS platform, so we can align our build for this project and others with the official image. 

PS: I want you to notice that we don't need to align with libraries of the official image for now because we only depend on libc which has a very impressive backward compatibility.

**Comment by fsenart** [comment]
I close the issue, we use the amazonlinux image in the new version of the project. https://github.com/eawsy/aws-lambda-go-shim
